/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:6f333f6b-f9d6-4ae6-bd40-9cac63b77743",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_LgBIIjhYX",
    "aws_user_pools_web_client_id": "3d2s59vi8pasj7nv6t5ohr287q",
    "oauth": {}
};


export default awsmobile;
